models:
  - name: products
    access: public
    description: Product catalog data mart, containing detailed information about all products sold at Jaffle Shop including pricing and categorization. One row per product.
    columns:
      - name: product_id
        description: The unique identifier for each product (SKU).
      - name: product_name
        description: The display name of the product.
      - name: product_type
        description: The category of product (e.g., 'jaffle', 'beverage').
      - name: product_description
        description: Detailed description of the product.
      - name: product_price
        description: The retail price of the product in USD.
      - name: is_food_item
        description: Boolean flag indicating if this product is a food item.
      - name: is_drink_item
        description: Boolean flag indicating if this product is a beverage item.

semantic_models:
  #The name of the semantic model.
  - name: products
    description: |
      Product dimension table. The grain of the table is one row per product.
    #The name of the dbt model and schema
    model: ref('products')
    #Entities. These usually corespond to keys in the table.
    entities:
      - name: product
        type: primary
        expr: product_id
    #Dimensions. Either categorical or time. These add additonal context to metrics. The typical querying pattern is Metric by Dimension.
    dimensions:
      - name: product_name
        type: categorical
      - name: product_type
        type: categorical
      - name: product_description
        type: categorical
      - name: is_food_item
        type: categorical
      - name: is_drink_item
        type: categorical
      - name: product_price
        type: categorical
